Adds completed final_sdss.csv file with all measurement
mwvgroup/SN-Spectral-Evolution pull request #57
Opened 2021-01-12 05:21 UTC by emilysf098

All SDSS measurements included in this pull request.

2021-01-12 12:54 UTC, djperrefort requested changes
This looks great! I'm guessing by the PR title this includes all of the SDSS Ia spectra? I have a few minor suggestions, but overall nothing major.

Nice job guys!

2021-01-12 12:54 UTC, djperrefort commented on notebooks/phase_evolution.ipynb
> +     "data": {
To avoid future conflicts, it might be better to clear the cells and add the unrendered notebook.

2021-01-12 12:54 UTC, djperrefort commented on test.csv
> +obj_id,time,feat_name,feat_start,feat_end,vel,vel_err,vel_samperr,pew,pew_err,pew_samperr,area,area_err,area_samperr,spec_flag,feat_flag,notes
Was including `test.csv` an intentional choice? If so, consider a more descriptive name.

2021-01-13 03:08 UTC, emilysf098 commented
We deleted the test.csv file (it wasn't necessary) and cleared the outputs from the phase_evolution.ipynb file.

2021-01-13 03:53 UTC, djperrefort approved these changes

2021-01-13 03:55 UTC, merged